"use client";

import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import styles from "./deck.module.css";

type Slide = { kicker: string; title: string; lead?: string; body: ReactNode };
const tx = {
  riskA: "91ae89f531480d490e5f89f67913d86e77fcf666778d7b5202a6951a8923f646",
  paidA: "6f514c89e296e43efc5d5af5cd60f9e5a3e13be8ca19daecc1355ed1d599cdc6",
  riskB: "c063f45b3ba73d73f932a534fe274ab7b9f748e5da9c2fdff48916efb0168a22",
  live: "66d28ffbb319d191ee62bc0833af6af031c463604cba5b2121f007ce705dd5ba",
};
const slides: Slide[] = [
  { kicker: "CARDANO RISK DESK", title: "An approval step before your agent pays anyone on Cardano", lead: "A paid check between the seller’s request and the wallet signature.", body: <p className={styles.prompt}>Use ← → to read. Press P to open the human Risk Desk.</p> },
  { kicker: "THE FEAR", title: "Your agent holds the wallet. The seller controls the story.", lead: "A payment request can name a real address, a real asset, and a real price while nobody has checked what sits behind them.", body: <div className={styles.columns}><Panel title="The agent sees">A 402 response with an amount, asset, payTo, and resource.</Panel><Panel title="The wallet can do">Sign and send value before a human inspects the counterparty.</Panel><Panel title="The missing step" accent>Check the asset policy, address history, and protocol surface before payment.</Panel></div> },
  { kicker: "THE PROBLEM IS REAL", title: "Payment rails do not tell an agent whether the purchase was wise.", lead: "The x402 community is already asking for refunds, chargebacks, and better payment intent. Cardano users already see imitation tokens and rug-pull warnings.", body: <div className={styles.proofGrid}><figure className={styles.proofImage}><img src="/proof/x402-issue-508.png" alt="x402 issue 508 discussing phishing-like scams behind paid pages" /><figcaption><Source href="https://github.com/x402-foundation/x402/issues/508" label="x402 issue #508" /> asks for a chargeback path.</figcaption></figure><figure className={styles.proofImage}><img src="/proof/x402-issue-3500.png" alt="x402 issue 3500 describing an agent paying for the wrong tier" /><figcaption><Source href="https://github.com/x402-foundation/x402/issues/3500" label="x402 issue #3500" /> describes a valid payment for the wrong purchase.</figcaption></figure><Panel title="38 / 100" accent>HN report: average x402 service fidelity across roughly 1,700 monitored services. <Source href="https://news.ycombinator.com/item?id=47158809" label="Read the thread" />.</Panel><figure className={styles.proofImage}><img src="/proof/cardano-rug-pulls.png" alt="Cardano scam and rug-pull evidence capture" /><figcaption>Cardano scam evidence capture from the local proof register.</figcaption></figure></div> },
  { kicker: "WHAT CAN GO WRONG ON CARDANO", title: "The risk is in the asset, the address, and the script.", lead: "The report turns chain facts into a refusal before the agent pays.", body: <div className={styles.columns}><Panel title="Open mint policy" accent><code>{"MIN.json\nscriptType=native\nrequiredSigners=1\nmintOpen=true"}</code><p>More supply can still be minted.</p></Panel><Panel title="Fresh address"><code>{"agent-demo/runs/1791341265898.json\nSeller B tx count: 1\nFirst seen: 2026-10-06"}</code><p>Newness becomes a condition, not a guess.</p></Panel><Panel title="Fake protocol script"><code>{"MINt.json\nmint-open / high\nliquidity: 1766.6595103971542 ADA"}</code><p>A familiar name does not make an asset safe.</p></Panel></div> },
  { kicker: "THE CHECK", title: "x402 becomes a payment gate, not just a payment rail.", lead: "The seller asks. The Risk Desk checks. The agent branches. Only one branch signs the seller payment.", body: <div className={styles.flow}>{[["402", "Seller asks", "asset · amount · payTo"], ["01", "Risk Desk", "paid assessment"], ["02", "Evidence", "policy · address · script"], ["03", "Decision", "interact or refuse"], ["04", "Payment", "sign only after check"]].map(([number, title, body], index) => <Panel key={number} title={number} accent={index === 3}>{title}<br /><br /><span>{body}</span></Panel>)}</div> },
  { kicker: "PREPROD RUN / agent-demo/runs/1791341265898.json", title: "The check sent one seller payment and stopped the other.", lead: "The same agent handled both 402 responses on Cardano preprod. Koios confirms every proof transaction.", body: <div className={styles.columns}><Panel title="Seller A / INTERACT" accent>Quote: 2,000,000 lovelace.<br /><br />Risk check <Tx h={tx.riskA} /><br />Seller paid <Tx h={tx.paidA} /></Panel><Panel title="Seller B / DO_NOT_INTERACT">Quote: 5 units of the custom token.<br /><br />Risk check <Tx h={tx.riskB} /><br />Reason: asset-mint-open.<br />Seller payment was not sent.</Panel><Panel title="The branch" dark>INTERACT → pay seller<br /><br />DO_NOT_INTERACT → refuse seller</Panel></div> },
  { kicker: "PRODUCTION PROOF / web/lib/x402/LIVE-PROOF.json", title: "The live endpoint settles once and rejects a replay.", lead: "The production x402 call returned INTERACT. The same payment presented again returned HTTP 409.", body: <div className={styles.columns}><Panel title="Cardano preprod" accent>Endpoint: cardano-risk-coworker.vercel.app/api/x402/risk-check<br /><br />Paid: HTTP 200<br />Decision: INTERACT<br />Koios confirmations: 1</Panel><Panel title="Replay protection" dark>Same payment<br /><br />HTTP 409<br /><br /><Tx h={tx.live} /></Panel></div> },
  { kicker: "ONE-LINE INTEGRATION", title: "Put the Risk Desk where the wallet would have signed.", lead: "The agent keeps its existing seller call. Add one paid check before the final payment.", body: <div className={styles.codeBlock}><code>{["curl -i https://cardano-risk-coworker.vercel.app/api/x402/risk-check \\", "  -H 'x-payment: <signed-cardano-payment>'"].join("\n")}</code><p>402 → pay the Risk Desk → read the assessment → continue or refuse.</p></div> },
  { kicker: "WHY CARDANO + MASUMI", title: "Cardano supplies the evidence. Masumi supplies the accountable work.", body: <div className={styles.columns}><Panel title="Cardano" accent>Native asset policies expose mint authority.<br /><br />Addresses and scripts are inspectable on chain.<br /><br />Koios turns those facts into cited evidence.</Panel><Panel title="Masumi">The Coworker is discoverable through Sokosumi.<br /><br />A task makes the decision accountable.<br /><br />Payment turns the check into a service an agent can hire.</Panel></div> },
  { kicker: "CLOSE", title: "Let the agent move fast. Make the wallet ask first.", lead: "Cardano Risk Analyst is the approval step before an autonomous payment becomes an irreversible one.", body: <div className={styles.closeLine}><span>REQUEST</span><b>→</b><span>CHECK</span><b>→</b><strong>APPROVE OR REFUSE</strong></div> },
];

export default function DeckPage() {
  const [index, setIndex] = useState(0);
  const slide = slides[index];
  const move = (delta: number) => setIndex((value) => Math.max(0, Math.min(value + delta, slides.length - 1)));
  useEffect(() => { function onKey(event: KeyboardEvent) { if (event.key === "ArrowRight" || event.key === " ") move(1); if (event.key === "ArrowLeft") move(-1); if (event.key.toLowerCase() === "p") window.location.href = "/"; } window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); });
  return <main className={styles.deck} aria-label="Cardano Risk Analyst pitch deck"><header className={styles.topbar}><a href="/">Cardano Risk Desk</a><span>APPROVAL BEFORE PAYMENT / {String(index + 1).padStart(2, "0")} OF 10</span><a href="/deck/cardano-risk-analyst.pptx" download>Download PPTX</a></header><section className={styles.slide} aria-live="polite"><div className={styles.content}><p className={styles.kicker}>{slide.kicker}</p><h1 className={styles.title}>{slide.title}</h1>{slide.lead && <p className={styles.lead}>{slide.lead}</p>}{slide.body}</div></section><footer className={styles.controls}><button onClick={() => move(-1)} disabled={index === 0} aria-label="Previous slide">←</button><span><strong>{String(index + 1).padStart(2, "0")}</strong> / 10</span><button onClick={() => move(1)} disabled={index === slides.length - 1} aria-label="Next slide">→</button><span className={styles.hint}>Arrow keys / space</span></footer></main>;
}
function Source({ href, label }: { href: string; label: string }) { return <a href={href} target="_blank" rel="noreferrer">{label}</a>; }
function Tx({ h }: { h: string }) { return <a href={"https://preprod.koios.rest/api/v1/tx_info?_tx_hashes=" + h} target="_blank" rel="noreferrer"><code>{h.slice(0, 12)}…</code></a>; }
function Panel({ title, children, accent = false, dark = false }: { title: string; children: ReactNode; accent?: boolean; dark?: boolean }) { return <article className={styles.panel + (accent ? " " + styles.accent : "") + (dark ? " " + styles.dark : "")}><h2>{title}</h2><div>{children}</div></article>; }
